### ISSUE TITLE
☂️ 22.Q4 Multivac and dashboards improvements

### ISSUE THREAD

**Issue by NickVolynkin** [tarantool/multivac#53]
Functional improvements

- [x] https://github.com/tarantool/multivac/issues/51
- [x] https://github.com/tarantool/multivac/issues/2
- [x] https://github.com/tarantool/multivac/issues/48
- [x] https://github.com/tarantool/multivac/issues/84
- [x] https://github.com/tarantool/multivac/issues/90

Performance, QoL, tech debt

- [x] https://github.com/tarantool/multivac/issues/52
- [ ] https://github.com/tarantool/multivac/issues/49
- [x] #54 
- [x] https://github.com/tarantool/multivac/issues/69
- [x] https://github.com/tarantool/multivac/issues/55
- [x] https://github.com/tarantool/multivac/issues/56
- [x] https://github.com/tarantool/multivac/issues/62
